name: Run Jupyter Notebook

on:
  schedule:
    - cron: '0 0 * * 1'  # At 00:00 (UTC) every Monday

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notebook papermill
        pip install -r requirements.txt
    
    - name: Execute Jupyter Notebook
      run: papermill visitseattle.ipynb output.ipynb
